import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import FristNav from "./_component/FristNav/FristNav";
import { Toaster } from "@/components/ui/toast"
import MyProvider from "./_component/MyProvider/MyProvider";
import Providers from "./_component/TanstackProvider/TanstackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body >
        <Providers>
        <MyProvider>

        <FristNav/>
        <Navbar/>
        <div className="container mx-auto">
        {children}
         <Toaster />
       </div>
        
        
        <Footer/>
        </MyProvider>
        </Providers>
        </body>
    </html>
  );
}
